const sampleData = {
  products: [
    {
      name: 'Affiliate Package',
      slug: 'affiliate',
      category: "Affiliate Packages",
      description: 'Perfect for individual who wants to try the product for themselves.',
      images: [
        '/images/sample-products/p1-1.png',
        '/images/sample-products/p1-2.png',
      ],
      price: 12,
      brand: 'Affiliate',
      rating: 4.5,
      numReviews: 20,
      stock: 1005,
      isFeatured: true,
      banner: 'banner-1.png',
    },
    {
      name: 'Bronze Package',
      slug: 'bronze',
      category: "Bronze Packages",
      description: 'Perfect for individual who wants to share the products with friends and family.',
      images: [
        '/images/sample-products/p2-1.png',
        '/images/sample-products/p2-2.png',
      ],
      price: 75,
      brand: 'Bronze',
      rating: 4.2,
      numReviews: 8,
      stock: 210,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Silver Package',
      slug: 'silver',
      category: "Silver Packages",
      description: 'Perfect for individual who are serious about sharing products with friends and family.',
      images: [
        '/images/sample-products/p3-1.png',
        '/images/sample-products/p3-2.png',
      ],
      price: 150,
      brand: 'Silver',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Gold Package',
      slug: 'gold',
      category: "Gold Packages",
      description: 'Perfect for individual who are serious about sharing the products to the community.',
      images: [
        '/images/sample-products/p4-1.png',
        '/images/sample-products/p4-2.png',
      ],
      price: 300,
      brand: 'Gold',
      rating: 4.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Gold Elite VIP Package',
      slug: 'gold-elite',
      category: "VIP Packages",
      description: 'Perfect for individual who is serious about doing the iGift business to the community.',
      images: [
        '/images/sample-products/p5-1.png',
        '/images/sample-products/p5-2.png',
      ],
      price: 900,
      brand: 'VIP',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Platinum VIP Package',
      slug: 'platinum-vip',
      category: "VIP",
      description: 'Perfect for individual who is serious about doing the iGift business to the community.',
      images: [
        '/images/sample-products/p6-1.png',
        '/images/sample-products/p6-2.png',
      ],
      price: 2100,
      brand: 'VIP',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
